name: Test MorphoSource API

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight
  workflow_dispatch:      # Allow manual triggering
  push:
    branches:
      - main
    paths:
      - 'tests/**'
      - '.github/workflows/**'

jobs:
  test-api:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pytest pytest-html pytest-cov
        
    - name: Run API tests
      env:
        MORPHOSOURCE_API_URL: ${{ secrets.MORPHOSOURCE_API_URL }}
        MORPHOSOURCE_API_TOKEN: ${{ secrets.MORPHOSOURCE_API_TOKEN }}
      run: |
        pytest tests/test_morphosource_api.py --html=test-results.html --cov=tests
        
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: test-results.html
        
    - name: Upload coverage report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: htmlcov/
